import "./globals.css";
import { Lexend, Inter } from "next/font/google";
import { AuthProvider } from "../context/AuthContext";

const lexend = Lexend({
  weight: ["400", "700"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AuthProvider>
        <body className={lexend.className}>{children}</body>
      </AuthProvider>
    </html>
  );
}
