version: '3'
services:
  frontend:
    image: luanaparra/frontend-p1:1.0  
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    image: luanaparra/backend-p1:1.0  
    container_name: backend
    ports:
      - "8000:8000"
    # depends_on:
    #   - banco-db
