FROM python:3.8-slim

WORKDIR /app

COPY requirements.txt /app/

RUN pip install --no-cache-dir -r requirements.txt

COPY . /app/

# Streamlit default port
EXPOSE 8501

CMD ["streamlit", "run", "dash.py"]
